version: '2'
services:
    versiontest-app:
        image: versiontest
        environment:
            - SPRING_PROFILES_ACTIVE=prod,swagger
            - SPRING_DATASOURCE_URL=jdbc:mysql://versiontest-mysql:3306/versiontest?useUnicode=true&characterEncoding=utf8&useSSL=false
            - JHIPSTER_SLEEP=10 # gives time for the database to boot before the application
        ports:
            - 8080:8080
    versiontest-mysql:
        extends:
            file: mysql.yml
            service: versiontest-mysql
